name: "Digital Ocean Deploy"
description: "Digital Ocean kubernetes deploy"
inputs:
  branch-develop:
    required: false
    description: "Develop branch"
    default: "develop"
  branch-production:
    required: false
    description: "Production branch"
    default: "master"
  kubeconfig: 
    required: true
    description: "kubernetes b64 config"
  do-token:
    required: true
    description: "Digital Ocean access token"
  consul-http-addr:
    required: true
    description: "Consul http address"
  consul-http-token:
    required: true
    description: "Consul http token"
  registry:
    required: true
    description: "Image registry"
  image-name: 
    required: true
    description: "Name of the image to build"
  image-tag-suffix: 
    required: false
    description: "suffix for the image tag"
  kube-resource:
    required: false
    description: "Kubernetes resources to rollout"
  kube-namespace-prefix:
    required: false
    default: "default"
    description: "Kubernetes namespace prefix"
  dockerfile-path:
    required: false
    description: "Path to the Dockerfile"
    default: 'Dockerfile'
  docker-username: 
    required: false
    description: "docker hub username"
  docker-password: 
    required: false
    description: "docker hub password"
  newrelic-license-key:
    required: false
    description: "New Relic license key"
  hs-token:
    required: false
    description: "helios token"
runs:
  using: composite
  steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Environment
      shell: bash
      run: |-
        if [ ${{ github.event_name }} == "pull_request" ]; then 
          branch=$(echo ${{ github.base_ref }}  | tr / -)
        else 
          branch=$(echo ${GITHUB_REF#refs/heads/} | tr / -)
        fi
        if [ $branch = ${{inputs.branch-production}} ]; then 
          env="production";
          consulenv="production";
          latest_tag="latest"
        elif [ $branch = ${{inputs.branch-develop}} ]; then 
          env="develop";
          consulenv="develop";
          latest_tag="${consulenv}-latest"
        else 
          env="develop";
          consulenv="develop";
          latest_tag="${consulenv}-latest"
        fi
        echo "ENV=$(echo $env)" >> $GITHUB_ENV
        echo "CONSULENV=$(echo $consulenv)" >> $GITHUB_ENV
        echo "LATEST_TAG=$(echo $latest_tag)" >> $GITHUB_ENV
        tag="${consulenv}${{inputs.image-tag-suffix}}"
        echo "TAG=$(echo $tag)" >> $GITHUB_ENV

    - name: Log in to Docker Hub
      if: inputs.docker-username || inputs.docker-password
      uses: docker/login-action@v2
      with:
        username: ${{ inputs.docker-username }}
        password: ${{ inputs.docker-password }}
    
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ inputs.do-token }}

    -
      name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        # Disable cache due to https://github.com/docker/build-push-action/issues/858. Issue Closed
        # cache-from: |
        #   type=registry,ref=${{inputs.registry}}/${{inputs.image-name}}:cache
        # cache-to: |
        #   type=registry,ref=${{inputs.registry}}/${{inputs.image-name}}:cache
        build-args: |
          NODE_ENV=${{ env.CONSULENV }}
          CONSUL_HTTP_ADDR=${{ inputs.consul-http-addr }}
          CONSUL_HTTP_TOKEN=${{ inputs.consul-http-token }}
          NEW_RELIC_LICENSE_KEY=${{ inputs.newrelic-license-key }}
          HS_TOKEN=${{ inputs.hs-token }}
        file: ${{ inputs.dockerfile-path }}
        tags: >-
          ${{inputs.registry}}/${{inputs.image-name}},${{inputs.registry}}/${{inputs.image-name}}:${{env.LATEST_TAG}},${{inputs.registry}}/${{inputs.image-name}}:${{env.TAG}}

    # - name: Build image
    #   shell: bash
    #   run: |
    #     docker buildx build \
    #       --build-arg NODE_ENV=${{ env.CONSULENV }} \
    #       --build-arg CONSUL_HTTP_ADDR=${{ inputs.consul-http-addr }} \
    #       --build-arg CONSUL_HTTP_TOKEN=${{ inputs.consul-http-token }} \
    #       --tag ${{inputs.registry}}/${{inputs.image-name}} \
    #       --tag ${{inputs.registry}}/${{inputs.image-name}}:${{env.LATEST_TAG}} \
    #       --tag ${{inputs.registry}}/${{inputs.image-name}}:${{env.TAG}} \
    #       --push \
    #       .


    - name: Set K8s resource image
      if: ${{inputs.kubeconfig && inputs.kube-resource}}
      uses: actions-hub/kubectl@master
      env:
        KUBE_CONFIG: ${{ inputs.kubeconfig }}
      with:
        args: -n ${{inputs.kube-namespace-prefix}}-${{env.CONSULENV}} set image ${{inputs.kube-resource}} *=${{inputs.registry}}/${{inputs.image-name}}:${{env.TAG}}

    - name: Set K8s worker resource image
      if: ${{inputs.kubeconfig && inputs.kube-resource && hashFiles('apps/${{inputs.image-name}}/worker.json') != ''}}
      uses: actions-hub/kubectl@master
      env:
        KUBE_CONFIG: ${{ inputs.kubeconfig }}
      with:
        args: -n ${{inputs.kube-namespace-prefix}}-${{env.CONSULENV}} set image ${{inputs.kube-resource}}-worker *=${{inputs.registry}}/${{inputs.image-name}}:${{env.TAG}}
    
    - name: Use Consul
      uses: docker://consul:1.11.2
      with:
        entrypoint: consul
        args: kv put -http-addr="${{inputs.consul-http-addr}}" -token="${{inputs.consul-http-token}}" "versions/${{inputs.image-name}}/${{env.CONSULENV}}/.tag" "${{env.TAG}}"

